'Arecanut', 'Pulses', 'Rice', 'Banana', 'Cashewnuts',
       'Coconut', 'Dry ginger', 'Sugarcane', 'Sweet Potato', 'Tapioca',
       'Black pepper', 'Dry chillies', 'Mustard seeds', 'Turmeric',
       'Maize', 'Moong', 'Urad', 'Tur', 'Groundnut', 'Sunflower', 'Bajra',
       'Castor seed', 'Cotton', 'Horse-gram', 'Jowar', 'Korra', 'Ragi',
       'Tobacco', 'Gram', 'Wheat', 'Masoor', 'Sesamum', 'Linseed',
       'Safflower', 'Onion', 'Samai', 'Small millets', 'Coriander',
       'Potato', 'Soyabean', 'Beans', 'Bhindi', 'Brinjal', 'Citrus Fruit',
       'Cucumber', 'Grapes', 'Mango', 'Orange', 'other fibres',
       'Other Fresh Fruits', 'Other Vegetables', 'Papaya', 'Pomegranate',
       'Tomato', 'Rapeseed', 'Mesta', 'Cowpea', 'Lemon', 'Sapota',
       'Cabbage', 'Peas', 'Niger seed', 'Bottle Gourd', 'Sannhamp',
       'Varagu', 'Garlic', 'Ginger', 'Jute', 'Blackgram', 'Paddy',
       'Pineapple', 'Barley', 'Khesari', 'Guar seed', 'Moth', 'Millets',
       'Cond-spcs other', 'Turnip', 'Carrot', 'Redish', 'Cardamom',
       'Rubber', 'Bitter Gourd', 'Drumstick', 'Jack Fruit', 'Snak Guard',
       'Pump Kin', 'Tea', 'Coffee', 'Cauliflower', 'Other Citrus Fruit',
       'Water Melon', 'Total foodgrain', 'Kapas', 'Colocosia', 'Lentil',
       'Jobster', 'Perilla', 'Rajmash Kholar', 'RiceBeans (nagadal)',
       'Ash Gourd', 'Beet Root', 'Lab-Lab', 'Ribed Guard', 'Yam', 'Apple',
       'Peach', 'Pear', 'Plums', 'Litchi', 'Ber', 'Other Dry Fruit'
23
'Rice', 'Jowar', 'Barley', 'Maize', 'Ragi', 'Chickpeas',
       'Fresh Beans', 'Beans', 'Soyabean', 'Black eyes beans',
       'Peas(Toor Dal)', 'Moong', 'Peas', 'Horse-gram(kulthi)',
       'Blackgram', 'Rapeseed', 'Coriander', 'Mustard seeds',
       'sesame seed', 'Cumin seeds', 'Lentils', 'Brinjal', 'Beetroot',
       'Bitter Gourd', 'Bottle Gourd', 'Capsicum', 'Cabbage', 'Carrot',
       'Cauliflower', 'Cucumber', 'Curry leaves', 'Drumstick',
       'Dry chillies', 'Lady Finger', 'Mushroom', 'Onion', 'Potato',
       'Pumpkin', 'Radish', 'Olive', 'Sweet Potato', 'Fenugreek',
       'Spinach', 'Ridgegourd', 'Gooseberry', 'Jambun',
       'Ziziphus mauritiana', 'Garcinia indica', 'Tamarind', 'Tapioca',
       'Garlic', 'Lemon', 'Tomato', 'Ash Gourd', 'Pineapple',
       'Pomegranate', 'Banana', 'Mango', 'Grapes', 'Jackfruit', 'Guava',
       'Water Melon', 'Musk Melon', 'Apricot', 'Apple', 'Chickoo',
       'Custard apple', 'Dates', 'Figs', 'Orange', 'Papaya', 'Aniseed',
       'Asafoetida', 'Bay Leaf', 'Black Pepper', 'Cardamom', 'Cinnamon',
       'Cloves', 'Jaiphal', 'Ginger', 'Turmeric', 'Cashewnuts', 'Raisins',
       'Coconut', 'Almond Nut', 'Arecanut', 'Pistachio Nut',
       'Lemon Grass', 'Cotton', 'Jute', 'Coffee', 'Sunflower'

Bajra',
 'Ber',
 'Castor seed',
 'Citrus Fruit',
 'Colocosia',
 'Cond-spcs other',
 'Cowpea',
 'Dry ginger',
 'Gram',
 'Groundnut',
 'Guar seed',
 'Jobster',
 'Kapas',
 'Khesari',
 'Korra',
 'Lab-Lab',
 'Lentil',
 'Linseed',
 'Litchi',
 'Mesta',
 'Millets',
 'Moth',
 'Niger seed',
 'Other Citrus Fruit',
 'Other Dry Fruit',
 'Other Fresh Fruits',
 'Other Vegetables',
 'Paddy',
 'Peach',
 'Pear',
 'Perilla',
 'Plums',
 'Pulses',
 'Rajmash Kholar',
 'Ribed Guard',
 'RiceBeans (nagadal)',
 'Rubber',
 'Samai',
 'Sannhamp',
 'Sapota',
 'Sesamum',
 'Small millets',
 'Snak Guard',
 'Sugarcane',
 'Tea',
 'Tobacco',
 'Total foodgrain',
 'Tur',
 'Turnip',
 'Urad',
 'Varagu',
 'Wheat',
 'Yam',
 nan,